//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace med_webb_CapaDato.Modelado
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Reseña = new HashSet<Reseña>();
        }
    
            [Key]
        public long Id { get; set; }
        [Required]
        public string nombre_del_cliente { get; set; }
        [Required]
        public string apellido_de_cliente { get; set; }

        public string correo_del_cliente { get; set; }
        public long PedidoId { get; set; }
        public long Usuario_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reseña> Reseña { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
