//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace med_webb_CapaDato.Modelado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Pedido_Plato
    {
        public int Id_detalle_factura_plato { get; set; }
        public string cantidad_detalle { get; set; }
        public string precio_unitario { get; set; }
        public string estado_pedido_plato { get; set; }
        public string metodo_de_pago { get; set; }
        public string reseña_cliente { get; set; }
        public int PedidoId { get; set; }
        public int PlatoId { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Plato Plato { get; set; }
    }
}
