//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace med_webb_CapaDato.Modelado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.Detalle_Pedido_Plato = new HashSet<Detalle_Pedido_Plato>();
        }
    
        public int Id { get; set; }
        public string descripcion_pedido { get; set; }
        public Nullable<System.DateTime> fecha_hora_pedido { get; set; }
        public string estado_del_pedido { get; set; }
        public string cantidad_pedido { get; set; }
        public int EmpleadoId { get; set; }
        public int ClienteId { get; set; }
        public int FacturaId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Pedido_Plato> Detalle_Pedido_Plato { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
