//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace med_webb_CapaDato.Modelado
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class Plato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plato()
        {
            this.Detalle_Pedido_Plato = new HashSet<Detalle_Pedido_Plato>();
        }
    
            [Key]
        public int Id { get; set; }
        public string nombre_del_plato { get; set; }
        public string descripcion_del_plato { get; set; }
        public string precio_del_plato { get; set; }
        public long Categoria_de_PlatoId { get; set; }
    
        public virtual Categoria_de_Plato Categoria_de_Plato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Pedido_Plato> Detalle_Pedido_Plato { get; set; }
    }
}
