//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace med_webb_CapaDato.Modelado
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class Reseña
    {
            [Key]
        public long Id { get; set; }
        public string fecha_reseña { get; set; }
        public string calificacion_reseña { get; set; }
        public string comentario { get; set; }
        public long ClienteId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
